# Generated by Django 3.1.5 on 2021-01-21 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('slug', models.SlugField(unique=True, verbose_name='Adres Anahtarı')),
                ('rank', models.PositiveSmallIntegerField(unique=True, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('slug', models.SlugField(unique=True, verbose_name='Adres Anahtarı')),
                ('image', models.ImageField(upload_to='', verbose_name='Afiş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_article', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_to_article', to='articles.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ['-created_at'],
            },
        ),
    ]
