# Generated by Django 3.1.5 on 2021-01-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Bu alan seçilirse makale yayınlanacaktır.', verbose_name='Yayın Durumu'),
        ),
    ]
