# Generated by Django 3.1.5 on 2021-01-22 15:09

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cropperjs.models.CropperImageField(aspectratio=1.7777, upload_to='', verbose_name='Afiş'),
        ),
    ]
