# Generated by Django 3.1.5 on 2021-01-22 18:22

import ckeditor.fields
import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210122_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cropperjs.models.CropperImageField(aspectratio=2.433333333333333, upload_to='', verbose_name='Afiş'),
        ),
    ]
