# Generated by Django 3.1.5 on 2021-01-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_auto_20210122_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_to_comments', to='articles.article', verbose_name='Makale')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_comments', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
