# Generated by Django 3.1.5 on 2021-01-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
    ]
