# Generated by Django 3.1.5 on 2021-01-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Sayfa')),
                ('slug', models.SlugField(unique=True, verbose_name='Adres Anahtarı')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('sort', models.PositiveSmallIntegerField(unique=True, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, help_text='Bu alan seçilirse sayfa yayınlanacaktır.', verbose_name='Sayfa Durumu')),
                ('show_top_position', models.BooleanField(default=True, help_text='Seçilirse anamenüde görünecek.', verbose_name='Header')),
                ('show_bottom_position', models.BooleanField(default=True, help_text='Seçilirse footerda görünecek.', verbose_name='Footer')),
                ('image', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
                'ordering': ['-sort'],
            },
        ),
    ]
