# Generated by Django 3.1.5 on 2021-01-22 15:11

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210122_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=cropperjs.models.CropperImageField(aspectratio=1.7777, upload_to='', verbose_name='Fotoğraf'),
        ),
    ]
